import {
  FaBluesky,
  FaFacebook,
  FaGithub,
  FaInstagram,
  FaLinkedin,
  FaMedium,
  FaSnapchat,
  FaTwitch,
  FaXTwitter,
  FaYoutube,
} from "react-icons/fa6";
import { SiFarcaster } from "react-icons/si";
import Odysee from "@/assets/Odysee";
import Mirror from "@/assets/Mirror";
import { RiMailFill, RiTelegram2Fill } from "react-icons/ri";
import { FaDiscord, FaLink, FaReddit } from "react-icons/fa";
const social = [
  {
    name: "X (Twitter)",
    icon: FaXTwitter,
    alt: "Twitter",
    description: "Share your Twitter/X profile or latest tweets",
    display: ["View", "Click"],
  },
  {
    name: "Telegram",
    icon: RiTelegram2Fill,
    alt: "Telegram",
    description: "Connect with your Telegram channel or group",
    display: ["View", "Click"],
  },
  {
    name: "Discord",
    icon: FaDiscord,
    alt: "Discord",
    description: "Link to your Discord server or profile",
    display: ["View", "Click"],
  },
  {
    name: "Farcaster",
    icon: SiFarcaster,
    alt: "Farcaster",
    description: "Display your Farcaster profile and casts",
    display: ["View", "Click"],
  },
  {
    name: "Medium",
    icon: FaMedium,
    alt: "Medium",
    description: "Showcase your Medium articles and publications",
    display: ["View", "Click"],
  },
  {
    name: "Mirror",
    icon: Mirror,
    alt: "Mirror",
    description: "Feature your Mirror blog posts and writings",
    display: ["View", "Click"],
  },
  {
    name: "Youtube",
    icon: FaYoutube,
    alt: "Youtube",
    description: "Embed your YouTube channel or videos",
    display: ["View", "Click"],
  },
  {
    name: "Github",
    icon: FaGithub,
    alt: "Github",
    description: "Show your GitHub repositories and contributions",
    display: ["View", "Click"],
  },
  {
    name: "Instagram",
    icon: FaInstagram,
    alt: "Instagram",
    description: "Display your Instagram posts and stories",
    display: ["View", "Click"],
  },
  {
    name: "Facebook",
    icon: FaFacebook,
    alt: "Facebook",
    description: "Connect your Facebook page or profile",
    display: ["View", "Click"],
  },
  {
    name: "Linkedin",
    icon: FaLinkedin,
    alt: "Linkedin",
    description: "Share your professional LinkedIn profile",
    display: ["View", "Click"],
  },
  {
    name: "Twitch",
    icon: FaTwitch,
    alt: "Twitch",
    description: "Link to your Twitch streams and highlights",
    display: ["View", "Click"],
  },
  {
    name: "Reddit",
    icon: FaReddit,
    alt: "Reddit",
    description: "Feature your Reddit posts and communities",
    display: ["View", "Click"],
  },
  {
    name: "Snapchat",
    icon: FaSnapchat,
    alt: "Snapchat",
    description: "Share your Snapchat profile and snaps",
    display: ["View", "Click"],
  },
  {
    name: "BlueSky",
    icon: FaBluesky,
    alt: "BlueSky",
    description: "Connect your BlueSky social profile",
    display: ["View", "Click"],
  },
  {
    name: "Url",
    icon: FaLink,
    alt: "Url",
    description: "Add any custom website or URL link",
    display: ["View", "Click"],
  },
  {
    name: "Email",
    icon: RiMailFill,
    alt: "Email",
    description: "Provide your email contact information",
    display: ["View", "Click"],
  },
  {
    name: "Odysee",
    icon: Odysee,
    alt: "Odysee",
    description: "Feature your Odysee videos and channel",
    display: ["View", "Click"],
  },
];
export default social;
